# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_release_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenote',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
