# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_release_notes', '0004_auto_20170821_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_play_url',
            field=models.CharField(blank=True, help_text='Enter the url to Google Play to automatically pull in new release notes as drafts.', max_length=1000),
        ),
    ]
