# Generated by Django 4.1.5 on 2026-04-07 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_release_notes", "0007_auto_20220225_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasenote",
            name="release_date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
