name: Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    env:
      DEBUG: "True"

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10.5'

    - name: Restore Dependency Cache
      id: cache-dependencies
      uses: actions/cache@v1.1.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-v2
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt --exists-action=w

    - name: Lint
      run: |
        make lint-ci

    - name: Test
      run: |
        make test-ci
